<a href="https://colab.research.google.com/github/Pradeep1694/Pradeep_Assignment.py/blob/main/SQL_Querying.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import sqlite3

customers_url = "https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/customers.csv"
orders_url = "https://raw.githubusercontent.com/graphql-compose/graphql-compose-examples/master/examples/northwind/data/csv/orders.csv"

customers_df = pd.read_csv(customers_url)
orders_df = pd.read_csv(orders_url)

conn = sqlite3.connect(":memory:")
customers_df.to_sql("customers", conn, index=False, if_exists="replace")
orders_df.to_sql("orders", conn, index=False, if_exists="replace")


#----------Task 1: ----------------


query="""
SELECT
    CustomerID,
    COUNT(OrderID) AS order_count,
    SUM(Freight) AS total_freight,
    AVG(Freight) AS avg_freight
FROM orders
GROUP BY CustomerID
ORDER BY total_freight DESC
LIMIT 10;
"""

query = pd.read_sql_query(query, conn)
display(query)

  customerID  order_count  total_freight  avg_freight
0      SAVEA           31        6683.70   215.603226
1      ERNSH           30        6205.39   206.846333
2      QUICK           28        5605.63   200.201071
3      HUNGO           19        2755.24   145.012632
4      RATTC           18        2134.21   118.567222
5      QUEEN           13        1982.70   152.515385
6      FOLKO           19        1678.08    88.320000
7      BERGS           18        1559.52    86.640000
8      FRANK           15        1403.44    93.562667
9      MEREP           13        1394.22   107.247692

In [7]:
#-----------Task 2 A: --------------

query_a ="""
SELECT CustomerID, COUNT(OrderID) AS high_freight_orders
FROM orders
WHERE Freight > 50
GROUP BY CustomerID
"""
query_a = pd.read_sql_query(query_a, conn)
display(query_a)

   customerID  high_freight_orders
0       ALFKI                    2
1       ANTON                    2
2       AROUT                    2
3       BERGS                   11
4       BLAUS                    1
..        ...                  ...
69      WANDK                    2
70      WARTH                    6
71      WELLI                    1
72      WHITC                    7
73      WOLZA                    1

[74 rows x 2 columns]

Query filters individual rows based on the Freight value before calculation happens

In [4]:
#-----------Task 2 B:------------

query_b ="""
SELECT CustomerID, SUM(Freight) AS total_freight
FROM orders
GROUP BY CustomerID
HAVING total_freight > 500;
"""
query_b = pd.read_sql_query(query_b, conn)
display(query_b)

   customerID  total_freight
0       BERGS        1559.52
1       BLONP         623.66
2       BONAP        1357.87
3       BOTTM         793.95
4       EASTC         832.34
5       ERNSH        6205.39
6       FOLIG         637.94
7       FOLKO        1678.08
8       FRANK        1403.44
9       GODOS         568.27
10      GREAL        1087.61
11      HANAR         724.77
12      HILAA        1259.16
13      HUNGO        2755.24
14      KOENE         813.68
15      LAMAI         635.82
16      LEHMS        1017.03
17      LILAS         734.41
18      LINOD         673.81
19      MEREP        1394.22
20      OLDWO         983.53
21      OTTIK         862.74
22      PICCO        1186.11
23      QUEEN        1982.70
24      QUICK        5605.63
25      RATTC        2134.21
26      RICAR         632.95
27      RICSU        1001.29
28      SAVEA        6683.70
29      SEVES         913.81
30      SPLIR         558.67
31      SUPRD         821.23
32      VAFFE         947.34
33      WARTH         822.48
34      WHITC        1353.06

Query groups all orders by customer first calculates the total and then filters out customers total spending is below 500

In [3]:
#-----------Task 3:-------------
inner_join_query = """
SELECT
c.CompanyName,
c.Country,
COUNT(o.OrderID) AS order_count,
SUM(o.Freight) AS total_freight
FROM customers c
INNER JOIN orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID;
"""
inner_join_query = pd.read_sql_query(inner_join_query, conn)
display(inner_join_query)

                           companyName  country  order_count  total_freight
0                  Alfreds Futterkiste  Germany            6         225.58
1   Ana Trujillo Emparedados y helados   Mexico            4          97.42
2              Antonio Moreno Taquería   Mexico            7         268.52
3                      Around the Horn       UK           13         471.95
4                   Berglunds snabbköp   Sweden           18        1559.52
..                                 ...      ...          ...            ...
84                      Wartian Herkku  Finland           15         822.48
85              Wellington Importadora   Brazil            9         194.71
86                White Clover Markets      USA           14        1353.06
87                         Wilman Kala  Finland            7          88.41
88                      Wolski  Zajazd   Poland            7         175.74

[89 rows x 4 columns]

Inner join only returns customers who have placed at least one order

In [2]:
#------------Task 3: -------------

left_join_query = """
SELECT
c.CompanyName,
c.Country,
COUNT(o.OrderID) AS order_count,
SUM(o.Freight) AS total_freight
FROM customers c
LEFT JOIN orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID;
"""
left_join_query = pd.read_sql_query(left_join_query, conn)
display(left_join_query)

                           companyName  country  order_count  total_freight
0                  Alfreds Futterkiste  Germany            6         225.58
1   Ana Trujillo Emparedados y helados   Mexico            4          97.42
2              Antonio Moreno Taquería   Mexico            7         268.52
3                      Around the Horn       UK           13         471.95
4                   Berglunds snabbköp   Sweden           18        1559.52
..                                 ...      ...          ...            ...
86                      Wartian Herkku  Finland           15         822.48
87              Wellington Importadora   Brazil            9         194.71
88                White Clover Markets      USA           14        1353.06
89                         Wilman Kala  Finland            7          88.41
90                      Wolski  Zajazd   Poland            7         175.74

[91 rows x 4 columns]

Left join returns every customer in the database those who have not placed an order and order count will be 0 and total freight will be NaN